In [1]:
# import dependencies
import pandas as pd

In [2]:
# Import base Fe dataset
compounds_df = pd.read_csv('Resources/Fe_coumpounds_dataframe.csv', index_col=0)
compounds_df.head()

,mp_id,Formula,Composition,IPF,Density,Elastic_Tensor,E_above_Hull,G_VRH,K_VRH,Elastic_Anisotropy,poisson_ratio,Y_Modulus
0,mp-1005,FeP,"{'Fe': 1.0, 'P': 1.0}",0.145502,6.371739,"{'G_Reuss': 130.0, 'G_VRH': 133.0, 'G_Voigt': ...",0.0,133.0,212.0,0.28,0.24,329.84
1,mp-1009077,FeH,"{'Fe': 1.0, 'H': 1.0}",0.195137,7.098567,"{'G_Reuss': 91.0, 'G_VRH': 91.0, 'G_Voigt': 91...",0.0,91.0,177.0,0.03,0.28,232.96
2,mp-11385,YFe5,"{'Y': 1.0, 'Fe': 5.0}",0.205646,7.107153,"{'G_Reuss': 67.0, 'G_VRH': 68.0, 'G_Voigt': 68...",0.0,68.0,105.0,0.13,0.23,167.28
3,mp-1418,FeNi3,"{'Fe': 1.0, 'Ni': 3.0}",0.173671,8.700536,"{'G_Reuss': 90.0, 'G_VRH': 96.0, 'G_Voigt': 10...",0.0,96.0,203.0,0.73,0.30,249.60
4,mp-1570,YFe2,"{'Y': 1.0, 'Fe': 2.0}",0.204319,6.872990,"{'G_Reuss': 35.0, 'G_VRH': 36.0, 'G_Voigt': 37...",0.0,36.0,92.0,0.25,0.33,95.76

In [3]:
# Extract composition column to be cleaned
composition_list = compounds_df["Composition"]
composition_list

0                             {'Fe': 1.0, 'P': 1.0}
1                             {'Fe': 1.0, 'H': 1.0}
2                             {'Y': 1.0, 'Fe': 5.0}
3                            {'Fe': 1.0, 'Ni': 3.0}
4                             {'Y': 1.0, 'Fe': 2.0}
                           ...
206     {'Tb': 2.0, 'Fe': 2.0, 'Si': 2.0, 'C': 1.0}
207    {'Ti': 1.0, 'Al': 1.0, 'Fe': 1.0, 'Co': 1.0}
208     {'Ho': 2.0, 'Fe': 2.0, 'Si': 2.0, 'C': 1.0}
209     {'Lu': 2.0, 'Fe': 2.0, 'Si': 2.0, 'C': 1.0}
210     {'Li': 1.0, 'Fe': 1.0, 'As': 2.0, 'O': 7.0}
Name: Composition, Length: 211, dtype: object

In [4]:
# Check successful extraction of composition data
composition_list[0]

"{'Fe': 1.0, 'P': 1.0}"

In [5]:
# create dataframe with every column being a element
element_columns = ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg',
            'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr',
            'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br',
            'Kr', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag',
            'Cd', 'In', 'Sn', 'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 
            'Tm', 'Yb', 'Lu', 'Hf', 'Ta', 'W',
            'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn',
            'Fr', 'Ra', 
            'Ac', 'Th', 'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 
            'Cf', 'Es', 'Fm', 'Md', 'No', 'Lr']
composition_df = pd.DataFrame(columns=element_columns)
composition_df

Empty DataFrame
Columns: [H, He, Li, Be, B, C, N, O, F, Ne, Na, Mg, Al, Si, P, S, Cl, Ar, K, Ca, Sc, Ti, V, Cr, Mn, Fe, Co, Ni, Cu, Zn, Ga, Ge, As, Se, Br, Kr, Rb, Sr, Y, Zr, Nb, Mo, Tc, Ru, Rh, Pd, Ag, Cd, In, Sn, Sb, Te, I, Xe, Cs, Ba, La, Ce, Pr, Nd, Pm, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb, Lu, Hf, Ta, W, Re, Os, Ir, Pt, Au, Hg, Tl, Pb, Bi, Po, At, Rn, Fr, Ra, Ac, Th, Pa, U, Np, Pu, Am, Cm, Bk, Cf, Es, Fm, ...]
Index: []

[0 rows x 103 columns]

In [6]:
# Check use of eval to convert string to dictionary
# Check successful conversion to dictionary
composition_list_dict = eval(composition_list[0])
composition_list_dict['P']

1.0

In [7]:
# loop over all data and apply eval to every row
for i in range(len(composition_list)):
    composition_list_dict[i] = eval(composition_list[i])

In [8]:
# check successful conversion
composition_list_dict[0]

{'Fe': 1.0, 'P': 1.0}

In [9]:
# check successful conversion
composition_list_dict[0]

{'Fe': 1.0, 'P': 1.0}

In [10]:
# for each row, append new dictionary into dataframe structure
for i in range(len(composition_list)):
    composition_df = composition_df.append(composition_list_dict[i],ignore_index=True)

    
composition_df

,H,He,Li,Be,B,C,N,O,F,Ne,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,NaN,NaN,1.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Fill NaN with 0
composition_df = composition_df.fillna(0)
composition_df

,H,He,Li,Be,B,C,N,O,F,Ne,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
207,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
208,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
209,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
210,0.0,0.0,1.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
# Pull list for mp_ids to add to final dataframe
mp_id_df = compounds_df['mp_id']
mp_id_df

0         mp-1005
1      mp-1009077
2        mp-11385
3         mp-1418
4         mp-1570
          ...
206       mp-6624
207     mp-998980
208    mp-1025316
209    mp-1025357
210      mp-18878
Name: mp_id, Length: 211, dtype: object

In [13]:
# Add mp_id to the composition datagframe
composition_df["mp_id"] = mp_id_df
    
composition_df

,H,He,Li,Be,B,C,N,O,F,Ne,...,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr,mp_id
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-1005
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-1009077
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-11385
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-1418
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-1570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-6624
207,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-998980
208,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-1025316
209,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-1025357
210,0.0,0.0,1.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mp-18878

In [14]:
# new column order
reorder_columns = ['mp_id', 'H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg',
            'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr',
            'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br',
            'Kr', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag',
            'Cd', 'In', 'Sn', 'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 
            'Tm', 'Yb', 'Lu', 'Hf', 'Ta', 'W',
            'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn',
            'Fr', 'Ra', 
            'Ac', 'Th', 'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 
            'Cf', 'Es', 'Fm', 'Md', 'No', 'Lr']

In [15]:
# recorder columns
composition_df = composition_df[reorder_columns]
composition_df

,mp_id,H,He,Li,Be,B,C,N,O,F,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,mp-1005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,mp-1009077,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,mp-11385,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,mp-1418,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,mp-1570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,mp-6624,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
207,mp-998980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
208,mp-1025316,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
209,mp-1025357,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
210,mp-18878,0.0,0.0,1.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
compounds_properties_df = compounds_df.drop(["Composition", "Elastic_Tensor"], axis=1)
compounds_properties_df.head()

,mp_id,Formula,IPF,Density,E_above_Hull,G_VRH,K_VRH,Elastic_Anisotropy,poisson_ratio,Y_Modulus
0,mp-1005,FeP,0.145502,6.371739,0.0,133.0,212.0,0.28,0.24,329.84
1,mp-1009077,FeH,0.195137,7.098567,0.0,91.0,177.0,0.03,0.28,232.96
2,mp-11385,YFe5,0.205646,7.107153,0.0,68.0,105.0,0.13,0.23,167.28
3,mp-1418,FeNi3,0.173671,8.700536,0.0,96.0,203.0,0.73,0.30,249.60
4,mp-1570,YFe2,0.204319,6.872990,0.0,36.0,92.0,0.25,0.33,95.76

In [17]:
# write to csv for database integration
composition_df.to_csv(r'Output/Fe_compounds_composition.csv', index = False)
compounds_properties_df.to_csv(r'Output/Fe_compounds_properties.csv', index = False)